import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@constants/Navbar";
import Footer from "@constants/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Service Provider",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
